name: Build and Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install --no-package-lock
        
      - name: Create dist directory
        run: mkdir -p dist
        
      - name: Build
        run: |
          npm run clean
          npm run build
          
      - name: Remove export line
        run: |
          sed -i 's/export { GoogleCard };//' dist/google-card.js
          
      - name: Format CSS
        run: |
          cat > format_css.pl << 'EOF'
          use strict;
          use warnings;
          
          local $/;  # Enable slurp mode
          my $content = <>;
          
          # Process each CSS template literal
          $content =~ s{
              (css\(_templateObject\$\d+\s*\|\|\s*\(_templateObject\$\d+\s*=\s*_taggedTemplateLiteral\(\[\s*)(['"])
              (.*?)
              \2\s*\]\)\)\)
          }{
              my $prefix = $1;
              my $quote = $2;
              my $css = $3;
              
              # Format the CSS
              $css =~ s/\\n/\n          /g;        # Replace \n with newlines
              $css =~ s/\Q$quote\E/\\$quote/g;     # Escape quotes
              $css =~ s/\s+$//mg;                  # Remove trailing spaces
              
              # Remove any unneeded escapes
              $css =~ s/\\([^$quote])/$1/g;
              
              # Reconstruct with proper formatting
              qq{$prefix$quote\n          $css\n        $quote])))};
          }gsex;
          
          # Clean up any double escapes
          $content =~ s/\\\\/\\/g;
          
          print $content;
          EOF
          
          # Run the formatter
          perl format_css.pl < dist/google-card.js > dist/google-card.formatted.js &&
          mv dist/google-card.formatted.js dist/google-card.js
          
      - name: Clean up template literals
        run: |
          # Fix any remaining syntax issues with template literals
          sed -i -E ':a;N;$!ba;s/\n[[:space:]]*\+[[:space:]]*\n[[:space:]]*\]/\n        ]/g' dist/google-card.js
          sed -i -E 's/([^\\])\s+\+\s*$/\1/g' dist/google-card.js
          sed -i -E 's/\\\n/\\n/g' dist/google-card.js
          
      - name: Verify JavaScript Syntax
        run: |
          node -c dist/google-card.js
          
      - name: Commit dist
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          if [ -f "dist/google-card.js" ] && node -c dist/google-card.js; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -f dist/google-card.js
            git commit -m "chore: update dist files" || echo "No changes to commit"
            git push
          else
            echo "dist/google-card.js not found or contains syntax errors"
            exit 1
          fi
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/google-card.js
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
