name: Build and Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Update package.json
        run: |
          cat > package.json << 'EOL'
          {
            "name": "google-card",
            "version": "0.1.5",
            "description": "A Home Assistant card that resembles Google's UI for photo frames and smart displays",
            "main": "dist/google-card.js",
            "scripts": {
              "build": "rollup -c",
              "build:dev": "rollup -c --environment DEV",
              "watch": "rollup -c -w",
              "lint": "eslint src",
              "lint:fix": "eslint src --fix",
              "format": "prettier --write \"src/**/*.js\"",
              "test": "echo \"No tests yet\" && exit 0"
            },
            "keywords": [
              "home-assistant",
              "lovelace",
              "card",
              "google"
            ],
            "author": "Your Name",
            "license": "MIT",
            "dependencies": {
              "lit-element": "2.4.0"
            },
            "devDependencies": {
              "@rollup/plugin-json": "6.1.0",
              "@rollup/plugin-node-resolve": "15.2.3",
              "@rollup/plugin-terser": "0.4.4",
              "eslint": "8.57.0",
              "eslint-config-prettier": "9.1.0",
              "eslint-plugin-import": "2.29.1",
              "eslint-plugin-prettier": "4.2.1",
              "prettier": "2.8.8",
              "rollup": "2.79.1",
              "rollup-plugin-copy": "3.5.0"
            }
          }
          EOL
          echo "Updated package.json"
      
      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
          echo "Dependencies installed successfully"
      
      - name: Fix source files
        run: |
          # Fix GoogleCard.js arrow functions
          echo "Fixing GoogleCard.js arrow functions"
          if grep -q "handleBrightnessCardToggle *=" src/GoogleCard.js; then
            sed -i 's/\(handleBrightnessCardToggle\) *=/\1/g' src/GoogleCard.js
            sed -i 's/\(handleBrightnessChange\) *=/\1/g' src/GoogleCard.js
            sed -i 's/\(handleDebugToggle\) *=/\1/g' src/GoogleCard.js
            sed -i 's/\(handleNightModeExit\) *=/\1/g' src/GoogleCard.js
            
            # Add method binding in constructor
            if ! grep -q "this.handleBrightnessCardToggle = this.handleBrightnessCardToggle.bind(this)" src/GoogleCard.js; then
              sed -i '/this.boundHandleThemeChange = this.handleThemeChange.bind(this);/a\
              \n    // Bind event handler methods\n    this.handleBrightnessCardToggle = this.handleBrightnessCardToggle.bind(this);\n    this.handleBrightnessChange = this.handleBrightnessChange.bind(this);\n    this.handleDebugToggle = this.handleDebugToggle.bind(this);\n    this.handleNightModeExit = this.handleNightModeExit.bind(this);' src/GoogleCard.js
            fi
          fi
          
          # Fix constants in BackgroundRotator.js
          echo "Fixing constants in BackgroundRotator.js"
          if grep -q "IMAGE_SOURCE_TYPES_MEDIA_SOURCE" src/components/BackgroundRotator.js; then
            sed -i 's/IMAGE_SOURCE_TYPES_MEDIA_SOURCE/IMAGE_SOURCE_TYPES.MEDIA_SOURCE/g' src/components/BackgroundRotator.js
            sed -i 's/IMAGE_SOURCE_TYPES_UNSPLASH_API/IMAGE_SOURCE_TYPES.UNSPLASH_API/g' src/components/BackgroundRotator.js
            sed -i 's/IMAGE_SOURCE_TYPES_IMMICH_API/IMAGE_SOURCE_TYPES.IMMICH_API/g' src/components/BackgroundRotator.js
            sed -i 's/IMAGE_SOURCE_TYPES_PICSUM/IMAGE_SOURCE_TYPES.PICSUM/g' src/components/BackgroundRotator.js
            sed -i 's/IMAGE_SOURCE_TYPES_URL/IMAGE_SOURCE_TYPES.URL/g' src/components/BackgroundRotator.js
          fi
          
          # Fix case statements with braces
          echo "Fixing case statements in BackgroundRotator.js"
          if grep -q "case IMAGE_SOURCE_TYPES.PICSUM:" src/components/BackgroundRotator.js; then
            # Add braces to PICSUM case if not already there
            if ! grep -q "case IMAGE_SOURCE_TYPES.PICSUM: {" src/components/BackgroundRotator.js; then
              sed -i '/case IMAGE_SOURCE_TYPES.PICSUM:/s/:/: {/' src/components/BackgroundRotator.js
              sed -i '/Array.from({ length: 10 }, () => this.getImageUrl());/s/$/\n      }/' src/components/BackgroundRotator.js
            fi
            
            # Add braces to default case if not already there
            if grep -q "default:" src/components/BackgroundRotator.js && ! grep -q "default: {" src/components/BackgroundRotator.js; then
              sed -i '/default:/s/:/: {/' src/components/BackgroundRotator.js
              sed -i '/return url ? \[ url \] : \[\];/s/$/\n      }/' src/components/BackgroundRotator.js
            fi
          fi
          
          echo "Source files fixed successfully"
      
      - name: Format and lint
        run: |
          npm run format
          npm run lint:fix
          echo "Formatting and linting completed"
      
      - name: Build
        run: |
          npm run build
          echo "Build completed successfully"
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Commit changes
        run: |
          git add package.json dist/google-card.js
          git commit -m "chore: update dependencies and build files" || echo "No changes to commit"
          git push || echo "No changes to push"
      
      - name: Verify build exists
        run: |
          if [ ! -f "dist/google-card.js" ]; then
            echo "Build verification failed - dist/google-card.js not found"
            exit 1
          fi
          echo "Build verification completed successfully"
      
      - name: Get version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: |
            Release of version ${{ steps.get_version.outputs.version }}
            
            Changes in this release:
            - Fixed dependency conflicts
            - Updated component registration
            - Fixed syntax issues in JavaScript files
            - Improved build process
          draft: false
          prerelease: false
