name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          echo "Dependencies installed successfully"

      - name: Lint and Format
        run: |
          npm run format
          npm run lint:fix
          echo "Linting and formatting completed successfully"

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Build
        run: |
          npm run build
          echo "Build completed successfully"

      - name: Stage changes
        run: |
          git add .
          git status

      - name: Commit changes
        run: |
          git commit -m "chore: update dist files and format source" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main || echo "No changes to push"

      - name: Verify build exists
        run: |
          if [ ! -f "dist/google-card.js" ]; then
            echo "Build verification failed - dist/google-card.js not found"
            exit 1
          fi
          echo "Build verification completed successfully"

      - name: Get version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: |
            Release of version ${{ steps.get_version.outputs.version }}
            
            Changes in this release:
            - Updated dist files
            - Formatted source files
          draft: false
          prerelease: false

      - name: Verify workflow completion
        run: |
          echo "All jobs completed successfully"
          echo "Version released: v${{ steps.get_version.outputs.version }}"
