name: Build and Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install --no-package-lock
        
      - name: Create dist directory
        run: mkdir -p dist
        
      - name: Build
        run: |
          npm run clean
          npm run build
          
      - name: Remove export line
        run: |
          sed -i 's/export { GoogleCard };//' dist/google-card.js
          
      - name: Format CSS
        run: |
          cat > format_css.pl << 'EOF'
          use strict;
          use warnings;
          
          local $/;
          my $content = <>;
          
          # First pass: Identify and format CSS template literals
          while ($content =~ m/(css\(_template[^`]*?`)(.*?)`\s*\]\)\)\)/gs) {
              my $prefix = $1;
              my $css = $2;
              
              # Format the CSS content
              $css =~ s/\n\s*/\n          /g;
              $css =~ s/^\s+//;
              $css =~ s/\s+$//;
              
              # Build the replacement
              my $replacement = "$prefix\n          $css\n        `])))";
              
              # Escape special regex characters in the prefix
              $prefix = quotemeta($prefix);
              # Replace in the content
              $content =~ s/$prefix.*?`\s*\]\)\)\)/$replacement/s;
          }
          
          print $content;
          EOF
          
          # Run the formatter
          perl format_css.pl < dist/google-card.js > dist/google-card.formatted.js &&
          mv dist/google-card.formatted.js dist/google-card.js
          
      - name: Clean up syntax
        run: |
          # Convert template literals to regular strings if needed
          sed -i 's/`/"/g' dist/google-card.js
          # Fix escaped quotes
          sed -i 's/\\"/\\\\"/g' dist/google-card.js
          # Fix newlines
          sed -i ':a;N;$!ba;s/\n/\\n/g' dist/google-card.js
          # Add proper line breaks back
          sed -i 's/\\n/\n/g' dist/google-card.js
          
      - name: Verify JavaScript Syntax
        run: |
          node -c dist/google-card.js
          
      - name: Commit dist
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          if [ -f "dist/google-card.js" ] && node -c dist/google-card.js; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -f dist/google-card.js
            git commit -m "chore: update dist files" || echo "No changes to commit"
            git push
          else
            echo "dist/google-card.js not found or contains syntax errors"
            exit 1
          fi
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/google-card.js
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
